language: node_js

node_js:
  - '10'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install codecov -g

install:
  - npm install
  - npm run build

after_success:
  - codecov

deploy:
    - provider: script
      script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
      on:
        all_branches: true

