language: node_js

node_js:
  - '8'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - npm install

deploy:
    - provider: script
      script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
      on:
        all_branches: true

